services:
  # 1. Node.js Express Backend Web Service
  - type: web
    name: civicpulse-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://sujankowshik10g26_db_user:BNr7iNpPNVOOiHVF@cluster0.1fzb5mz.mongodb.net/civicpulse?appName=Cluster0
      - key: JWT_SECRET
        value: super_secret_civic_pulse_key_2026
      - key: PORT
        value: 10000

  # 2. Vite Frontend Static Site
  - type: web
    name: civicpulse-frontend
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: civicpulse-backend
          property: host
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
